# -*- coding: utf-8 -*-
"""검색용 랜딩 6쪽 — 한 검색 의도에 한 쪽. 모든 주장은 앱 실물(s131 기준)에 맞춘다: 없는 기능은 '없다'고 쓴다."""

PAGES = [
 dict(slug="ipad-cad", img="hotel-parking-sheet", img2="layers-sheet", orient="land", orient2="land",
  ko=dict(
   title="아이패드 캐드 앱 | 아이패드용 CAD로 DWG·DXF 편집, Apple Pencil 마크업 - 플럭스케치 Fluxketch",
   desc="아이패드 캐드 앱 플럭스케치(Fluxketch). 아이패드에서 DWG·DXF 도면을 열고 CAD 편집, 정밀 스냅, Apple Pencil 마크업, 현장 핀, 축척 플롯까지 — 현장 사람을 위한 아이패드용 캐드입니다. 비공개 베타 진행 중.",
   eyebrow="아이패드 캐드", k="아이패드 캐드", short="아이패드 캐드 앱",
   h1="아이패드 캐드 — 아이패드에서 CAD 도면을 열고 직접 수정하세요",
   lead="플럭스케치(Fluxketch)는 iPad와 Apple Pencil을 위해 만든 아이패드용 2D 캐드(CAD)입니다. 사무실의 DWG·DXF를 그대로 열고, 선·원·치수를 CAD 문법 그대로 그리고 고치고, 축척 맞춘 PDF와 DXF로 돌려보냅니다.",
   alt="Fluxketch 도면 보기 — 호텔 지하 주차장 평면도와 CAD 도구 팔레트", alt2="레이어 패널 — 188개 레이어의 가시성·색·굵기·선종류",
   qa_h2="아이패드 캐드에 대해 가장 많이 묻는 것",
   qa=[
    ("아이패드에서 캐드 작업이 정말 가능한가요?","네. 플럭스케치(Fluxketch)는 아이패드용 캐드 앱이고, 뷰어가 아니라 편집기입니다. 선·폴리선·원·호·사각형·문자·이동·복사·모깎기·자르기·지우기·치수 12개 도구와 끝점·직교 스냅, 수치 키패드로 사무실 CAD와 같은 방식으로 그립니다. 18만 도형 도면에서도 팬·줌이 60Hz로 따라옵니다."),
    ("DWG 파일은 어떻게 여나요?","파일 앱·iCloud·메일 첨부에서 DWG를 고르면 Fluxketch 변환 서버가 DXF로 바꿔 엽니다(이때만 인터넷 필요). DXF와 PDF는 완전히 오프라인으로 엽니다. 레이어·색·굵기·선종류·블록·해치·다중선을 가져오고, 못 가져온 요소는 가져오기 리포트에 개수로 표시됩니다."),
    ("DXF 편집이 가능한가요?","네. DXF는 읽을 때 단위(mm·cm·m·inch·ft)를 묻고 좌표를 보정합니다. 도형을 선택해 이동·복사·자르기·지우기를 하고, 결과를 다시 DXF로 내보내 사무실 CAD에서 이어 그립니다."),
    ("선이 벡터로 유지되나요?","유지됩니다. Metal 벡터 렌더러가 선을 그리고, 큰 도면은 래스터 타일이 함께 그리다가 멈추는 즉시 벡터로 선명해집니다. 도면 보기(시트 뷰)로 바꾸면 인쇄물처럼 흰 바탕에 검은 선으로 봅니다."),
    ("치수를 넣거나 수정할 수 있나요?","치수 도구로 두 점을 찍으면 실제 길이가 단위와 함께 들어갑니다. 실척 자는 1:1부터 1:1,000까지 축척으로 화면을 보여 주고, 종이 위 100mm 눈금으로 프린터 배율까지 검증합니다."),
    ("Apple Pencil을 쓸 수 있나요?","CAD 도구와 마크업 모두 Apple Pencil로 씁니다. 마크업의 펜·마커·연필 획은 도면 좌표에 고정돼 확대·이동 중에도 갈라지지 않고, 펜슬로는 화면이 밀리지 않도록 팬은 손가락에만 배정돼 있습니다."),
    ("축척 맞춰 출력할 수 있나요?","플롯 PDF는 축척과 100mm 검증 눈금을 달고 나갑니다. 마크업 잉크와 핀도 그대로 인쇄됩니다. 시트 발행으로 특정 시트만 PDF로 내보낼 수도 있습니다."),
    ("어떤 iPad가 필요한가요?","iPad와 Apple Pencil이면 됩니다. 큰 도면은 M 시리즈 iPad에서 가장 쾌적하고, 베타에서는 iPad 9세대와 A16 기종에서도 검증합니다. iPadOS 전용이며 iPhone·Android·Windows 버전은 없습니다."),
    ("아이패드용 캐드 앱을 고를 때 무엇을 봐야 하나요?","세 가지입니다. ① DWG·DXF를 레이어·선종류 그대로 여는가 ② 보기만 하는 뷰어가 아니라 스냅·치수가 있는 편집기인가 ③ 축척 맞춘 PDF와 DXF로 사무실에 돌려보낼 수 있는가. 플럭스케치는 이 셋을 기준으로 만든 아이패드 캐드입니다."),
   ],
   steps_h2="시작은 세 단계입니다",
   steps=[("도면 열기","파일 앱에서 DWG·DXF·PDF를 고릅니다. DXF는 단위를 확인하고, 가져오기 리포트가 레이어와 요소 개수를 보여 줍니다."),
          ("그리고 고치기","왼쪽 팔레트의 12개 도구와 오른쪽 스냅 레일로 그립니다. 레이어 패널에서 가시성·잠금·색·굵기·선종류를 바로 바꿉니다."),
          ("꺼내기","플롯 PDF·DXF 내보내기·시트 발행·리포트로 사무실과 현장에 보냅니다.")],
  ),
  en=dict(
   title="CAD for iPad | Edit DWG & DXF, mark up with Apple Pencil - Fluxketch",
   desc="Open DWG and DXF drawings on iPad, edit with real CAD tools and snaps, mark up with Apple Pencil, drop site pins and plot to scale. Fluxketch is field CAD for iPad. Private beta.",
   eyebrow="CAD for iPad", k="iPad CAD", short="CAD for iPad",
   h1="Open and edit CAD drawings on your iPad",
   lead="Fluxketch is a 2D CAD built for iPad and Apple Pencil. Open the office's DWG and DXF as they are, draw and edit lines, circles and dimensions with the CAD grammar you know, and send scale-true PDF and DXF back.",
   alt="Fluxketch sheet view — hotel basement parking plan with the CAD tool palette", alt2="Layer panel — visibility, color, weight and linetype for 188 layers",
   qa_h2="What people ask about CAD on iPad",
   qa=[
    ("Can you really do CAD work on an iPad?","Yes. Fluxketch is an editor, not a viewer. Twelve tools — line, polyline, circle, arc, rectangle, text, move, copy, fillet, trim, erase, dimension — with endpoint and ortho snaps and a numeric keypad, the same way you draw on desktop CAD. Pan and zoom hold 60 Hz on a 180,000-entity drawing."),
    ("How do I open a DWG file?","Pick a DWG from the Files app, iCloud or a mail attachment and the Fluxketch conversion server turns it into DXF for opening (the only step that needs a connection). DXF and PDF open fully offline. Layers, colors, weights, linetypes, blocks, hatches and multilines come across; anything that can't be imported is counted in the import report."),
    ("Can I edit DXF?","Yes. DXF asks for its unit (mm, cm, m, inch, ft) on read and corrects coordinates. Select entities to move, copy, trim or erase, then export back to DXF and keep drawing in office CAD."),
    ("Do lines stay vector?","They do. A Metal vector renderer draws the lines; on large drawings a raster tile pyramid draws alongside and snaps back to sharp vector the moment you stop. Switch to sheet view for black lines on white, like a print."),
    ("Can I add or change dimensions?","The dimension tool takes two points and writes the real length with units. The true-scale ruler shows the screen at 1:1 to 1:1,000, and a 100 mm check ruler on paper verifies even printer scaling."),
    ("Does it work with Apple Pencil?","Both CAD tools and markup use Apple Pencil. Pen, marker and pencil strokes are locked to drawing coordinates, so they never drift while zooming or panning, and the Pencil never pans the canvas — panning is for fingers."),
    ("Can I print to scale?","Plot PDFs carry the chosen scale and a 100 mm check ruler. Markup ink and pins print as they are. Sheet issue exports only the sheets you pick."),
    ("Which iPad do I need?","Any iPad with an Apple Pencil. Large drawings are most comfortable on M-series iPads; the beta is also verified on iPad 9th generation and A16 models. iPadOS only — there is no iPhone, Android or Windows version."),
   ],
   steps_h2="Three steps to start",
   steps=[("Open a drawing","Pick a DWG, DXF or PDF in the Files app. DXF confirms its unit, and the import report lists layers and entity counts."),
          ("Draw and edit","Twelve tools in the left palette and the snap rail on the right. Change visibility, lock, color, weight and linetype in the layer panel."),
          ("Export","Plot PDF, DXF export, sheet issue and reports go straight to the office and the site.")],
  )),
 dict(slug="mobile-cad", img="parking-portrait-dark", img2="menu-report", orient="port", orient2="land",
  ko=dict(
   title="모바일 캐드 앱 | 현장에서 도면 열고 수정하는 아이패드 CAD - 플럭스케치 Fluxketch",
   desc="모바일 캐드(CAD)가 뷰어에 그치지 않으려면 편집·스냅·레이어·축척 출력이 필요합니다. 플럭스케치(Fluxketch)는 아이패드에서 DWG·DXF를 열고 그리고 마크업하고 축척 PDF로 꺼내는 모바일 캐드 앱입니다.",
   eyebrow="모바일 캐드", k="모바일 캐드", short="모바일 캐드 앱",
   h1="모바일 캐드는 뷰어가 아니라 편집기여야 합니다",
   lead="현장에서 필요한 건 도면을 '보는' 앱이 아니라 그 자리에서 고치고 표시하고 꺼내는 앱입니다. Fluxketch는 iPad 하나로 사무실 CAD의 도면을 받아 손대고 돌려보냅니다.",
   alt="세로로 든 iPad의 Fluxketch CAD 모드 — 주차장 평면도", alt2="더보기 메뉴 — 핀 로그·리포트·시트 발행·플롯·DXF 내보내기",
   qa_h2="모바일 CAD를 고를 때 확인할 것",
   qa=[
    ("모바일 CAD와 CAD 뷰어는 무엇이 다른가요?","뷰어는 열고 재는 데서 끝납니다. Fluxketch는 선·원·치수를 그리고, 도형을 이동·복사·자르기하고, 레이어를 켜고 끄고 색·굵기·선종류를 바꾸고, 결과를 DXF와 축척 PDF로 다시 내보냅니다."),
    ("스마트폰에서도 되나요?","아니요. Fluxketch는 iPad 전용입니다. 도면은 화면이 커야 하고 Apple Pencil의 정밀도가 필요하기 때문에 iPhone·Android 버전은 만들지 않았습니다."),
    ("인터넷이 없는 현장에서도 쓸 수 있나요?","DXF·PDF 열기, 작도, 마크업, 핀, 플롯은 전부 오프라인입니다. DWG를 처음 열 때만 변환 서버 연결이 필요하므로, 현장에 나가기 전에 한 번 열어 두거나 PC에서 DXF로 저장해 가져가세요."),
    ("큰 도면도 버티나요?","18만 도형 도면에서 팬·줌 60Hz, 레이어 188개를 그대로 다루는 도면으로 검증했습니다. 메모리 관문이 기기 가용량을 보고 열 수 있는지 먼저 판단하고, 안 되면 이유를 말합니다."),
    ("현장 기록은 어떻게 남기나요?","핀을 찍고 사진과 메모를 답니다. 핀은 도면 좌표에 고정돼 위치가 곧 기록이고, 핀 로그가 곧 목록이며 점검·지시·회의 등 7종 문서 서식의 리포트로 인쇄됩니다."),
    ("사무실 CAD로 돌아가면 어떻게 되나요?","DXF로 내보내면 레이어·색·굵기·선종류가 그대로 따라갑니다. 마크업 잉크와 핀은 플롯 PDF에 인쇄됩니다. DWG 저장은 아직 지원하지 않으므로 PC CAD에서 DXF를 열어 DWG로 저장하세요."),
    ("세로로 들고도 쓸 수 있나요?","네. 세로 모드에서는 도구 묶음이 오른쪽 세로 열로 옮겨 가고 팔레트가 우측에서 펼쳐집니다. 한 손으로 잡고 다른 손으로 Apple Pencil을 쓰는 자세에 맞췄습니다."),
    ("한국어와 영어 모두 되나요?","네. 앱과 문서 서식 모두 한국어·영어를 지원하고, 첫 실행에서 고른 언어를 설정에서 다시 바꿀 수 있습니다."),
   ],
   steps_h2="현장에서의 하루",
   steps=[("아침, 사무실에서","오늘 도면을 DWG·DXF로 iPad에 담습니다. DWG는 여기서 한 번 열어 변환해 둡니다."),
          ("현장에서","핀·사진·마크업·치수를 도면 좌표에 남깁니다. 실척 자로 1:50 그대로 보면서 확인합니다."),
          ("저녁, 회의에서","리포트 한 부와 플롯 PDF로 회의하고, DXF는 사무실 CAD로 돌려보냅니다.")],
  ),
  en=dict(
   title="Mobile CAD app | Open and edit drawings on site with iPad - Fluxketch",
   desc="A mobile CAD that is more than a viewer needs editing, snaps, layers and scale-true output. Fluxketch opens DWG and DXF on iPad, draws, marks up and exports scale PDFs.",
   eyebrow="Mobile CAD", k="Mobile CAD", short="Mobile CAD app",
   h1="Mobile CAD should be an editor, not a viewer",
   lead="On site you don't need an app that shows the drawing — you need one that fixes, marks and exports it where you stand. Fluxketch takes the office's drawings on one iPad, works on them and sends them back.",
   alt="Fluxketch CAD mode on an iPad held upright — parking plan", alt2="More menu — pin log, report, sheet issue, plot, DXF export",
   qa_h2="What to check when choosing a mobile CAD",
   qa=[
    ("How is a mobile CAD different from a CAD viewer?","A viewer opens and measures, then stops. Fluxketch draws lines, circles and dimensions, moves, copies and trims entities, toggles layers and changes their color, weight and linetype, then exports the result to DXF and scale-true PDF."),
    ("Does it run on a phone?","No. Fluxketch is iPad-only. Drawings need a large screen and the precision of Apple Pencil, so there is no iPhone or Android version."),
    ("Does it work on a site without a connection?","Opening DXF and PDF, drafting, markup, pins and plotting are all offline. Only the first opening of a DWG needs the conversion server, so open it once before you leave or save as DXF on a PC."),
    ("Can it take big drawings?","Verified at 60 Hz pan and zoom on a 180,000-entity drawing and on a drawing with 188 layers handled as-is. A memory gate checks the device's free memory before opening and tells you why if it can't."),
    ("How do I keep site records?","Drop a pin and attach a photo and a note. Pins are locked to drawing coordinates, so the position is the record; the pin log is the list, and it prints as a report in seven document formats (inspection, instruction, meeting and more)."),
    ("What happens back in office CAD?","DXF export carries layers, colors, weights and linetypes. Markup ink and pins print into the plot PDF. Saving to DWG is not supported yet — open the DXF in PC CAD and save as DWG."),
    ("Can I hold it upright?","Yes. In portrait the tool cluster moves to a vertical column on the right and palettes open from the right edge, matching a one-hand hold with the Pencil in the other."),
    ("Korean and English?","Both. The app and its document formats are localized in Korean and English, and the language chosen on first launch can be changed in Settings."),
   ],
   steps_h2="A day on site",
   steps=[("Morning, at the office","Put today's drawings on the iPad as DWG or DXF. Open a DWG once here to convert it."),
          ("On site","Leave pins, photos, markup and dimensions on drawing coordinates. Check at 1:50 with the true-scale ruler."),
          ("Evening, in the meeting","One report and a plot PDF run the meeting; the DXF goes back to office CAD.")],
  )),
 dict(slug="dwg-ipad", img="layers-sheet", img2="vivienda-dark", orient="land", orient2="land",
  ko=dict(
   title="아이패드에서 DWG 열기·편집 | 레이어·선종류 그대로 - 플럭스케치 Fluxketch",
   desc="아이패드에서 DWG 파일을 레이어·색·굵기·선종류 그대로 열고, 캐드 도구로 편집하고, Apple Pencil로 마크업해 축척 PDF·DXF로 꺼내는 방법. 아이패드 DWG 캐드 앱 플럭스케치(Fluxketch).",
   eyebrow="아이패드 DWG", k="DWG 아이패드", short="아이패드 DWG",
   h1="아이패드에서 DWG를 레이어 그대로 엽니다",
   lead="DWG는 AutoCAD의 이진 형식이라 모바일에서 열면 레이어나 선종류가 사라지기 일쑤입니다. Fluxketch는 DWG를 DXF로 정확히 변환해 레이어·색·굵기·선종류·블록·해치를 그대로 가져옵니다.",
   alt="DWG를 연 뒤의 레이어 패널 — 레이어 188개의 색·굵기·선종류", alt2="주택 도면 CAD 모드 — 전기·설비 시트",
   qa_h2="DWG를 iPad에서 열 때 궁금한 것",
   qa=[
    ("DWG를 열면 무엇이 살아 있나요?","레이어(가시성·잠금·색·굵기·선종류), 도형 색과 자기 색, 블록 삽입, 해치, 다중선(MLINE), 3D면, 지시선, 문자와 치수를 가져옵니다. 임의 좌표계(OCS)로 그려진 도형도 위치를 바로잡아 옵니다."),
    ("가져오지 못하는 것도 있나요?","있습니다. 다중 지시선(MULTILEADER)·와이프아웃·리전은 아직 지원하지 않습니다. 못 가져온 요소는 숨기지 않고 가져오기 리포트에 종류와 개수로 표시합니다. 동결·꺼진 레이어의 도형은 가져오되 화면에서 숨겨 두고, 그 사실을 알려 줍니다."),
    ("어떤 DWG 버전을 지원하나요?","변환은 오픈소스 LibreDWG 기반이며 AutoCAD R14부터 2018 형식까지 읽습니다. 변환은 Fluxketch 변환 서버에서 하고 결과 DXF만 iPad로 돌아옵니다."),
    ("인터넷이 필요한가요?","DWG를 처음 열 때만 필요합니다. 변환된 뒤로는 오프라인에서 열고 그리고 마크업합니다. 인터넷이 없는 현장이라면 PC에서 DXF로 저장해 가져가면 처음부터 오프라인입니다."),
    ("DWG로 다시 저장할 수 있나요?","아직은 DXF로 내보냅니다. DXF는 AutoCAD·BricsCAD·ZWCAD 등 모든 CAD가 그대로 열므로 거기서 DWG로 저장하세요. 마크업과 핀은 플롯 PDF에 함께 인쇄됩니다."),
    ("파일이 크면요?","수십 MB DWG는 변환하면 DXF가 4~6배 커집니다. Fluxketch는 파일 크기가 아니라 도형 개수와 기기 가용 메모리로 열 수 있는지 판단해 140만 도형 도면까지 열었습니다. 열 수 없으면 이유를 표시합니다."),
    ("잘린 DWG나 깨진 파일은요?","메일·메신저를 거치며 잘린 파일은 변환 서버가 '파일 끝이 없다'고 알려 주고, 앱은 iCloud에서 내려받기가 끝날 때까지 기다린 뒤 읽습니다. 원본을 다시 받아 열면 됩니다."),
    ("PDF로 받은 도면은요?","PDF는 밑그림(언더레이)으로 열어 두 점으로 축척을 맞추고 벡터 선에 스냅해 그 위에 그립니다. 자세한 것은 아이패드 DXF 페이지에 있습니다."),
   ],
   steps_h2="DWG 여는 순서",
   steps=[("파일 고르기","대시보드의 가져오기에서 파일 앱·iCloud·메일 첨부의 DWG를 고릅니다."),
          ("변환과 리포트","서버가 DXF로 변환하고, 가져오기 리포트가 레이어 수·도형 수·가져오지 못한 요소를 보여 줍니다."),
          ("편집·마크업·꺼내기","CAD 도구로 고치고 Apple Pencil로 표시한 뒤 DXF와 플롯 PDF로 내보냅니다.")],
  ),
  en=dict(
   title="Open and edit DWG on iPad | Layers and linetypes intact - Fluxketch",
   desc="How to open DWG files on iPad with layers, colors, weights and linetypes intact, edit them with CAD tools, mark up with Apple Pencil and export scale PDF and DXF. Fluxketch, the DWG app for iPad.",
   eyebrow="DWG on iPad", k="DWG iPad", short="DWG on iPad",
   h1="Open DWG on iPad with every layer intact",
   lead="DWG is AutoCAD's binary format, and mobile apps often drop layers or linetypes when they open it. Fluxketch converts DWG to DXF precisely and brings layers, colors, weights, linetypes, blocks and hatches across as they are.",
   alt="Layer panel after opening a DWG — color, weight and linetype for 188 layers", alt2="House drawing in CAD mode — electrical and MEP sheet",
   qa_h2="Questions about DWG on iPad",
   qa=[
    ("What survives when I open a DWG?","Layers (visibility, lock, color, weight, linetype), by-layer and explicit entity colors, block inserts, hatches, multilines (MLINE), 3D faces, leaders, text and dimensions. Entities drawn in an arbitrary coordinate system (OCS) are placed correctly too."),
    ("Is anything not imported?","Yes. Multileaders, wipeouts and regions are not supported yet. Nothing is hidden: the import report lists what was skipped by type and count. Entities on frozen or off layers are imported but kept hidden, and the app tells you so."),
    ("Which DWG versions are supported?","Conversion is based on open-source LibreDWG and reads AutoCAD R14 through 2018 formats. It runs on the Fluxketch conversion server and only the resulting DXF comes back to the iPad."),
    ("Do I need a connection?","Only when a DWG is first opened. After conversion you open, draw and mark up offline. For a site without coverage, save as DXF on a PC and it's offline from the start."),
    ("Can I save back to DWG?","Export is DXF for now. Every CAD — AutoCAD, BricsCAD, ZWCAD and others — opens DXF directly, so save as DWG there. Markup and pins print into the plot PDF."),
    ("What about large files?","A DWG of tens of megabytes grows four to six times as DXF. Fluxketch decides by entity count and the device's free memory, not file size, and has opened drawings of 1.4 million entities. If it can't, it tells you why."),
    ("What about truncated or damaged DWGs?","Files cut short by mail or chat apps are flagged by the conversion server as missing their end-of-file, and the app waits for iCloud downloads to finish before reading. Get the original again and open it."),
    ("What if all I have is a PDF?","Open it as an underlay, set the scale with two points and snap to its vector lines while you draw. See the DXF on iPad page for details."),
   ],
   steps_h2="How a DWG opens",
   steps=[("Pick the file","Use Import on the dashboard to choose a DWG from the Files app, iCloud or a mail attachment."),
          ("Convert and report","The server converts to DXF, and the import report shows layer count, entity count and anything skipped."),
          ("Edit, mark up, export","Fix with CAD tools, mark with Apple Pencil, then export DXF and a plot PDF.")],
  )),
 dict(slug="dxf-ipad", img="structural-dark", img2="sections-sheet", orient="land", orient2="land",
  ko=dict(
   title="아이패드에서 DXF 열기·편집·내보내기 | 오프라인 - 플럭스케치 Fluxketch",
   desc="아이패드에서 DXF 도면을 오프라인으로 열고 단위를 보정해 캐드 편집, 마크업, 축척 플롯까지. 편집 결과를 DXF로 다시 내보내 사무실 CAD와 왕복하는 아이패드 캐드 앱 플럭스케치(Fluxketch).",
   eyebrow="아이패드 DXF", k="DXF 아이패드", short="아이패드 DXF",
   h1="DXF는 iPad에서 오프라인으로 열고, DXF로 돌려보냅니다",
   lead="DXF는 열린 텍스트 형식이라 Fluxketch가 직접 읽습니다. 서버도, 인터넷도 필요 없습니다. 단위를 확인하고 좌표를 보정해 열고, 고친 결과를 DXF로 다시 내보냅니다.",
   alt="구조 배근 상세 DXF를 연 CAD 모드", alt2="단면·입면 시트 — 도면 보기",
   qa_h2="DXF를 iPad에서 다룰 때 궁금한 것",
   qa=[
    ("DXF 단위가 틀려서 도면이 커지거나 작아지지 않나요?","DXF는 읽는 순간 단위(mm·cm·m·inch·ft)를 묻고 좌표를 그 단위로 보정합니다. 도면 중심을 기준으로 보정하므로 원점이 먼 도면도 제자리에 옵니다. 실척 자와 플롯이 그 단위를 그대로 씁니다."),
    ("어떤 DXF 요소를 읽나요?","선·폴리선·LW폴리선·원·호·타원·스플라인·문자·다중문자·치수·해치·블록 삽입·다중선·3D면·지시선과 레이어 테이블(색·굵기·선종류)을 읽습니다. 다중 지시선·와이프아웃·리전은 리포트에 개수로 남깁니다."),
    ("DXF 버전은요?","AutoCAD 2000 이후 형식으로 저장한 ASCII DXF로 검증했습니다. 열리지 않는 파일은 flux0720@fluxketch.com으로 보내 주시면 확인해 드립니다."),
    ("편집한 뒤 DXF로 내보내면 무엇이 따라가나요?","레이어·색·굵기·선종류가 따라갑니다. 마크업 잉크와 핀은 도면 좌표 기준 별도 데이터로 파일 안에 보관되고 플롯 PDF로 인쇄됩니다."),
    ("큰 DXF도 열리나요?","파일 관문은 512MiB이지만 실제 판단은 도형 개수와 기기 가용 메모리로 합니다. 140만 도형 DXF까지 열렸고, 열 수 없으면 이유를 표시합니다."),
    ("PDF 도면밖에 없을 때는요?","PDF는 밑그림(언더레이)으로 열어 두 점으로 축척을 맞추고, PDF 안의 벡터 선에 스냅해 그 위에 CAD로 그립니다. 그린 결과는 DXF로 내보냅니다."),
    ("DWG는요?","DWG는 변환 서버를 거쳐 DXF로 엽니다(처음 열 때만 인터넷 필요). 자세한 내용은 아이패드 DWG 페이지에 있습니다."),
    ("숨긴 레이어는 어떻게 되나요?","레이어를 끄면 화면·스냅·플롯이 같은 규칙으로 그 레이어를 뺍니다. 잠근 레이어는 보이지만 선택·수정이 막힙니다. AutoCAD와 같은 규칙입니다."),
   ],
   steps_h2="DXF 왕복 순서",
   steps=[("DXF 열기","파일 앱에서 DXF를 고르고 단위를 확인합니다. 인터넷은 필요 없습니다."),
          ("고치기","CAD 도구 12종과 스냅으로 그리고, 레이어 패널에서 색·굵기·선종류를 바꿉니다."),
          ("DXF로 내보내기","더보기 메뉴의 DXF 내보내기로 사무실 CAD에 돌려보냅니다.")],
  ),
  en=dict(
   title="Open, edit and export DXF on iPad | Offline - Fluxketch",
   desc="Open DXF drawings on iPad offline, correct the unit, edit with CAD tools, mark up and plot to scale. Export back to DXF and round-trip with office CAD. Fluxketch.",
   eyebrow="DXF on iPad", k="DXF iPad", short="DXF on iPad",
   h1="DXF opens offline on iPad and goes back as DXF",
   lead="DXF is an open text format, so Fluxketch reads it directly — no server, no connection. It confirms the unit, corrects coordinates, and exports what you changed back to DXF.",
   alt="Structural rebar detail DXF in CAD mode", alt2="Sections and elevations sheet in sheet view",
   qa_h2="Questions about DXF on iPad",
   qa=[
    ("Won't a wrong DXF unit make the drawing huge or tiny?","DXF asks for its unit (mm, cm, m, inch, ft) on read and corrects coordinates in that unit. Correction is centered on the drawing, so drawings far from the origin land where they should. The true-scale ruler and plots use the same unit."),
    ("Which DXF entities are read?","Lines, polylines, LW polylines, circles, arcs, ellipses, splines, text, mtext, dimensions, hatches, block inserts, multilines, 3D faces, leaders and the layer table (color, weight, linetype). Multileaders, wipeouts and regions are counted in the report."),
    ("Which DXF versions?","Verified with ASCII DXF saved in AutoCAD 2000 or later formats. If a file won't open, send it to flux0720@fluxketch.com and we'll look."),
    ("What goes back when I export DXF?","Layers, colors, weights and linetypes. Markup ink and pins are stored inside the file as separate data in drawing coordinates and print into the plot PDF."),
    ("Do large DXFs open?","The file gate is 512 MiB, but the real decision is entity count against the device's free memory. DXFs of 1.4 million entities have opened; if one can't, the app says why."),
    ("What if I only have a PDF?","Open it as an underlay, set the scale with two points and snap to the PDF's vector lines while drawing CAD on top. Export what you drew as DXF."),
    ("And DWG?","DWG opens through the conversion server as DXF (a connection is needed only on first open). See the DWG on iPad page."),
    ("What happens to hidden layers?","Turn a layer off and the screen, snaps and plots all exclude it by the same rule. A locked layer stays visible but can't be selected or edited — the AutoCAD rule."),
   ],
   steps_h2="The DXF round trip",
   steps=[("Open the DXF","Pick it in the Files app and confirm the unit. No connection needed."),
          ("Edit","Draw with the twelve CAD tools and snaps; change color, weight and linetype in the layer panel."),
          ("Export DXF","DXF export in the More menu sends it back to office CAD.")],
  )),
 dict(slug="cad-markup", img="vivienda-markup-dark", img2="hotel-markup-sheet", orient="land", orient2="land",
  ko=dict(
   title="캐드 도면 마크업 앱 | Apple Pencil로 도면 좌표에 - 플럭스케치 Fluxketch",
   desc="Apple Pencil로 캐드(CAD) 도면 위에 펜·마커·연필 마크업을 하고, 사진 핀과 노트를 도면 좌표에 붙여 리포트로 인쇄하는 아이패드 앱. 획이 도면과 갈라지지 않는 플럭스케치(Fluxketch) 마크업.",
   eyebrow="CAD 도면 마크업", k="CAD 마크업", short="CAD 도면 마크업",
   h1="마크업이 도면에 붙어 있어야 기록입니다",
   lead="스크린샷 위에 그린 표시는 다음 날 어디였는지 모릅니다. Fluxketch의 마크업은 도면 좌표에 고정돼 확대·이동·축척 변경 뒤에도 같은 자리에 있고, 플롯 PDF에 그대로 인쇄됩니다.",
   alt="마크업 모드 — 아파트 평면 위 마커 표시와 색·굵기 팔레트", alt2="도면 보기 위의 마크업 — 호텔 기준층",
   qa_h2="도면 마크업에 대해 묻는 것",
   qa=[
    ("마크업 도구는 무엇이 있나요?","펜·마커·연필·지우개·올가미·자입니다. Apple Pencil 필압을 그대로 쓰고, 색과 굵기는 팔레트에서 고릅니다. 되돌리기·다시 실행이 마크업에도 적용됩니다."),
    ("확대하면 획이 도면과 어긋나지 않나요?","어긋나지 않습니다. 획은 화면이 아니라 도면 좌표에 저장되고, 굵기도 도면 단위 기준입니다. 확대·축소·이동 중에도 획이 도면과 함께 움직이고, 그리는 동안 기존 잉크가 떨리지 않도록 입력 면을 따로 두었습니다."),
    ("손가락과 펜슬이 섞이지 않나요?","화면 이동은 손가락, 그리기는 Apple Pencil입니다. 펜슬로는 화면이 밀리지 않습니다. 한 손가락 이동 모드에서도 올가미·지우개·이동은 펜슬로 계속 됩니다."),
    ("사진은 어떻게 붙이나요?","핀을 찍고 사진과 메모를 답니다. 핀은 언제나 마크업 위에 그려지고 도면 좌표에 고정됩니다. 핀 로그가 목록이 되고, 리포트에는 사진·메모·위치가 함께 인쇄됩니다."),
    ("노트는 따로 쓸 수 있나요?","노트 페이지(백지·줄·도트·모눈·제도 모눈)를 도면 파일 안에 추가합니다. 회의 메모나 스케치를 도면과 한 파일에 둡니다."),
    ("마크업은 사무실 CAD에서 보이나요?","마크업 잉크와 핀은 플롯 PDF와 리포트에 인쇄됩니다. DXF 내보내기에는 CAD 도형이 나가고, 손글씨는 PDF로 전달하는 것이 현장 관행에 맞아 그렇게 두었습니다."),
    ("PDF 도면에도 마크업할 수 있나요?","네. PDF를 밑그림으로 열어 두 점으로 축척을 맞추면 그 위에 마크업·핀·CAD 작도를 할 수 있습니다."),
    ("도면 보기와 CAD 모드 어디서 하나요?","둘 다입니다. 흰 바탕 도면 보기에서는 인쇄물 위에 쓰듯, 어두운 CAD 모드에서는 레이어 색 그대로 위에 씁니다. 모드를 오가도 획은 제자리입니다."),
   ],
   steps_h2="마크업에서 리포트까지",
   steps=[("마크업 모드로","하단의 마크업 탭을 누르면 펜·마커·연필·지우개·올가미·자 팔레트가 열립니다."),
          ("그리고 찍기","Apple Pencil로 표시하고, 핀에 사진과 메모를 답니다."),
          ("리포트로","더보기 메뉴에서 리포트를 고르면 점검·지시·회의 등 7종 문서 서식으로 인쇄됩니다.")],
  ),
  en=dict(
   title="CAD markup app | Apple Pencil on drawing coordinates - Fluxketch",
   desc="Mark up CAD drawings with Apple Pencil — pen, marker, pencil — pin photos and notes to drawing coordinates and print them as reports. Fluxketch markup never drifts from the drawing.",
   eyebrow="CAD markup", k="CAD markup", short="CAD markup on iPad",
   h1="Markup is only a record if it sticks to the drawing",
   lead="A mark on a screenshot doesn't know where it was the next day. Fluxketch markup is locked to drawing coordinates — same place after zoom, pan or a scale change — and prints as-is into the plot PDF.",
   alt="Markup mode — marker notes on an apartment plan with the color and width palette", alt2="Markup over sheet view — hotel typical floor",
   qa_h2="Questions about drawing markup",
   qa=[
    ("Which markup tools are there?","Pen, marker, pencil, eraser, lasso and ruler. Apple Pencil pressure is used as-is, and color and width come from the palette. Undo and redo apply to markup too."),
    ("Do strokes drift from the drawing when I zoom?","No. Strokes are stored in drawing coordinates, not screen pixels, and widths are in drawing units. They move with the drawing through zoom and pan, and a separate input surface keeps existing ink steady while you draw."),
    ("Fingers versus Pencil?","Fingers pan; Apple Pencil draws. The Pencil never pushes the canvas. In one-finger pan mode, lasso, eraser and move still work with the Pencil."),
    ("How do I attach photos?","Drop a pin and add a photo and a note. Pins always draw above markup and are locked to drawing coordinates. The pin log is the list, and reports print photo, note and position together."),
    ("Can I take separate notes?","Add note pages — blank, ruled, dotted, grid, drafting grid — inside the drawing file, so meeting notes and sketches live with the drawing."),
    ("Does markup show up in office CAD?","Markup ink and pins print into plot PDFs and reports. DXF export carries CAD entities; handwriting travels as PDF, which matches how sites actually work."),
    ("Can I mark up a PDF drawing?","Yes. Open the PDF as an underlay, set the scale with two points, and mark up, pin and draft on top."),
    ("Sheet view or CAD mode?","Both. On white sheet view you write as if on a print; in dark CAD mode you write over the layer colors. Strokes stay put when you switch."),
   ],
   steps_h2="From markup to report",
   steps=[("Enter markup","Tap the Markup tab at the bottom to open pen, marker, pencil, eraser, lasso and ruler."),
          ("Draw and pin","Mark with Apple Pencil, then add photos and notes to pins."),
          ("Make the report","Choose Report in the More menu and print in seven document formats — inspection, instruction, meeting and more.")],
  )),
 dict(slug="cad-plot", img="ruler-popover", img2="hotel-sheet-portrait", orient="land", orient2="port",
  ko=dict(
   title="아이패드에서 캐드 도면 축척 PDF 출력(플롯) | 100mm 검증 눈금 - 플럭스케치 Fluxketch",
   desc="아이패드에서 캐드(CAD) 도면을 1:50, 1:100 축척 그대로 PDF로 플롯하고 100mm 검증 눈금으로 프린터 배율까지 확인하는 방법. 마크업·핀까지 인쇄되는 플럭스케치(Fluxketch) 플롯.",
   eyebrow="축척 플롯", k="CAD 플롯", short="축척 PDF 플롯",
   h1="축척이 맞는 종이가 현장의 기준입니다",
   lead="화면에서 자로 재도 종이에서 틀리면 소용이 없습니다. Fluxketch의 플롯 PDF는 지정한 축척으로 나가고, 종이 위 100mm 눈금이 우리 축척과 프린터 배율을 갈라 줍니다.",
   alt="실척 자 팝오버 — 1:1부터 1:1,000 축척과 자로 맞추기", alt2="세로 iPad의 도면 보기 — 호텔 시트",
   qa_h2="플롯과 축척에 대해 묻는 것",
   qa=[
    ("축척은 어떻게 정하나요?","플롯에서 1:1부터 1:1,000까지 축척과 용지를 고릅니다. DXF를 열 때 확인한 단위가 그대로 쓰이므로 mm 도면은 mm 기준으로 나갑니다."),
    ("프린터가 '페이지에 맞춤'으로 줄여 버리면요?","그래서 100mm 검증 눈금을 인쇄합니다. 출력물의 눈금을 자로 재서 100mm가 아니면 프린터 배율이 걸린 것이니 '실제 크기'로 다시 뽑으면 됩니다."),
    ("마크업과 핀도 인쇄되나요?","네. 마크업 잉크와 핀이 도면과 같은 좌표로 인쇄됩니다. 도면 보기(시트 뷰)의 흰 바탕·검은 선 규칙이 적용되고, 바탕 테두리는 넣지 않습니다."),
    ("특정 시트만 뽑을 수 있나요?","시트 발행으로 원하는 시트만 골라 PDF로 냅니다. 리포트는 별도 문서로, 핀 사진·메모·위치가 표 서식으로 나갑니다."),
    ("화면에서 실척으로 볼 수도 있나요?","실척 자가 기종별 화면 밀도를 추정해 1:50이면 1:50으로 보여 줍니다. 자로 맞추기로 실제 자와 대조해 보정할 수 있습니다."),
    ("큰 도면 플롯은 화면을 멈추나요?","아니요. 플롯은 백그라운드에서 렌더링하므로 그동안 화면이 멈추지 않고, 끝나면 공유 시트가 열립니다."),
    ("PDF는 어디로 보내나요?","iOS 공유 시트로 메일·메신저·파일 앱·AirPrint 프린터로 보냅니다. 회의 자료는 리포트와 함께 한 번에 보내면 됩니다."),
    ("DXF로도 돌려보낼 수 있나요?","네. 플롯 PDF와 별개로 DXF 내보내기가 있어 레이어·굵기·선종류 그대로 사무실 CAD로 돌아갑니다."),
   ],
   steps_h2="플롯 순서",
   steps=[("축척·용지 고르기","더보기 메뉴의 플롯에서 1:50, 1:100 같은 축척과 용지를 고릅니다."),
          ("검증 눈금 확인","출력물의 100mm 눈금을 자로 재서 프린터 배율이 걸리지 않았는지 확인합니다."),
          ("공유","공유 시트로 프린터·메일·메신저·파일 앱에 보냅니다.")],
  ),
  en=dict(
   title="Plot CAD drawings to scale PDF on iPad | 100 mm check ruler - Fluxketch",
   desc="How to plot CAD drawings from iPad to PDF at 1:50 or 1:100 and verify printer scaling with a 100 mm check ruler. Fluxketch plots print markup and pins too.",
   eyebrow="Scale plot", k="CAD plot", short="Scale PDF plot",
   h1="Paper at the right scale is the site's reference",
   lead="Measuring on screen is worthless if the paper is wrong. Fluxketch plot PDFs go out at the scale you set, and a 100 mm ruler on the paper separates our scale from the printer's.",
   alt="True-scale ruler popover — 1:1 to 1:1,000 and ruler calibration", alt2="Sheet view on an upright iPad — hotel sheet",
   qa_h2="Questions about plotting and scale",
   qa=[
    ("How do I set the scale?","Choose a scale from 1:1 to 1:1,000 and a paper size in Plot. The unit confirmed when the DXF was opened is used as-is, so a millimetre drawing plots in millimetres."),
    ("What if the printer shrinks it with 'fit to page'?","That's why a 100 mm check ruler is printed. Measure it on the paper; if it isn't 100 mm, printer scaling kicked in — reprint at actual size."),
    ("Are markup and pins printed?","Yes. Ink and pins print at the same coordinates as the drawing. Sheet-view rules apply — black lines on white — with no page border."),
    ("Can I plot only certain sheets?","Sheet issue exports just the sheets you choose. Reports are a separate document with pin photos, notes and positions in table layouts."),
    ("Can I see true scale on screen?","The true-scale ruler estimates each device's screen density, so 1:50 shows as 1:50. Calibrate against a real ruler if needed."),
    ("Does a big plot freeze the screen?","No. Plotting renders in the background, so the screen stays responsive, and the share sheet opens when it's done."),
    ("Where does the PDF go?","Through the iOS share sheet to Mail, chat apps, the Files app or an AirPrint printer. Send it with the report for a meeting."),
    ("Can I also send it back as DXF?","Yes. DXF export is separate from the plot PDF and returns to office CAD with layers, weights and linetypes intact."),
   ],
   steps_h2="How to plot",
   steps=[("Pick scale and paper","Open Plot in the More menu and choose a scale such as 1:50 or 1:100 and a paper size."),
          ("Check the ruler","Measure the 100 mm ruler on the print to confirm the printer didn't rescale."),
          ("Share","Send through the share sheet to a printer, Mail, chat or the Files app.")],
  )),
]
