# -*- coding: utf-8 -*-
"""가이드 글 6편(한/영). 정보글 90% + 마지막 10%만 Fluxketch. 블록: h2/p/ul/ol/note/fig/table. p·li 안의 <a>는 그대로 나간다."""
DATE = "2026-09-10"

GUIDES = [
 dict(slug="open-dwg-on-ipad", img="layers-sheet",
  ko=dict(
   title="아이패드에서 DWG 파일 여는 방법 — CAD 도면을 바로 확인하고 수정하기",
   short="아이패드에서 DWG 여는 방법", desc="iPad에서 DWG 파일을 여는 세 가지 방법과 레이어·선종류가 사라지는 이유, 그리고 레이어를 유지한 채 열고 수정하는 순서를 정리했습니다.",
   h1="아이패드에서 DWG 파일 여는 방법",
   lead="현장에서 받은 DWG를 iPad에서 열어야 할 때 무엇이 되고 무엇이 안 되는지, 레이어를 잃지 않고 여는 방법을 순서대로 정리했습니다.",
   body=[
    ("h2","DWG란 무엇인가"),
    ("p","DWG는 AutoCAD의 기본 저장 형식입니다. 이진(binary) 형식이라 사람이 읽을 수 없고, 버전(R14·2000·2004·2007·2010·2013·2018)마다 내부 구조가 다릅니다. 그래서 AutoCAD가 아닌 프로그램이 DWG를 열려면 형식을 해석하는 별도 엔진이 필요하고, 이 엔진의 품질이 곧 '레이어가 살아 있는가, 선종류가 맞는가'를 결정합니다."),
    ("p","같은 도면을 텍스트로 풀어 쓴 것이 DXF입니다. 열린 형식이라 어떤 CAD든 읽고 쓸 수 있습니다. 둘의 차이는 <a href=\"/guides/dwg-vs-dxf/\">DWG와 DXF의 차이</a>에서 따로 다룹니다."),
    ("h2","iPad에서 DWG를 열 때 흔히 생기는 문제"),
    ("ul",["<b>레이어가 사라진다.</b> 뷰어가 DWG를 그림 한 장으로 평탄화해 버리면 레이어를 끄고 켤 수 없고, 도면을 돌려보낼 수도 없습니다.",
          "<b>선 굵기·선종류가 전부 같아진다.</b> 파선·일점쇄선이 실선으로, 굵은 벽선이 가는 선으로 보이면 도면 읽기가 틀어집니다.",
          "<b>일부 선이 안 보인다.</b> 다중선(MLINE)·3D면·임의 좌표계(OCS)로 그린 도형을 건너뛰는 앱이 많습니다. 사라진 선은 알려 주지 않으면 모릅니다.",
          "<b>축척이 틀어진다.</b> mm 도면을 m로 읽으면 1,000배 작아집니다. 단위를 묻지 않는 앱은 여기서 틀립니다.",
          "<b>큰 파일이 안 열린다.</b> DWG를 DXF로 바꾸면 4~6배 커지는데, 이 크기로 '너무 크다'고 거부하는 앱이 있습니다."]),
    ("h2","iPad에서 DWG를 여는 세 가지 길"),
    ("ol",["<b>PC에서 DXF로 저장해 가져간다.</b> 가장 확실합니다. AutoCAD에서 '다른 이름으로 저장 → DXF(2018 ASCII)'로 저장하고 iCloud·AirDrop으로 iPad에 옮깁니다. 인터넷 없는 현장에서도 처음부터 오프라인으로 열립니다.",
          "<b>DWG를 직접 여는 앱을 쓴다.</b> 앱이 DWG를 변환해 엽니다. 변환을 기기에서 하는지 서버에서 하는지, 변환 뒤 레이어·선종류가 유지되는지, 못 가져온 요소를 알려 주는지가 앱마다 다릅니다.",
          "<b>PDF로 출력해 간다.</b> 편집은 포기하고 보기만 할 때의 선택입니다. 축척을 알면 PDF 위에 마크업은 할 수 있습니다."]),
    ("h2","레이어를 유지한 채 여는 순서(Fluxketch 기준)"),
    ("fig","layers-sheet","DWG를 연 뒤 레이어 패널 — 레이어 188개의 색·굵기·선종류","DWG를 열면 레이어 188개가 색·굵기·선종류와 함께 그대로 옵니다."),
    ("ol",["대시보드에서 <b>가져오기</b>를 누르고 파일 앱·iCloud·메일 첨부의 DWG를 고릅니다. iCloud에 아직 내려받지 않은 파일이면 내려받기가 끝날 때까지 기다린 뒤 읽습니다.",
          "변환 서버가 DWG를 DXF로 바꿉니다(LibreDWG 기반, R14~2018). 이때만 인터넷이 필요합니다.",
          "<b>가져오기 리포트</b>가 레이어 수·도형 수와 함께 '가져오지 못한 요소'를 종류와 개수로 보여 줍니다. 다중 지시선·와이프아웃·리전은 아직 지원하지 않으므로 여기서 확인합니다.",
          "동결·꺼진 레이어의 도형은 가져오되 화면에서 숨겨 두고 그 사실을 알립니다. 레이어 패널에서 켜면 바로 보입니다."]),
    ("note","메일이나 메신저를 거치며 <b>잘린 DWG</b>는 어떤 앱에서도 열리지 않습니다. 변환 서버가 '파일 끝이 없다'고 알려 주면 원본을 다시 받으세요."),
    ("h2","CAD 객체 선택과 수정"),
    ("p","열린 뒤에는 뷰어가 아니라 CAD입니다. 선·폴리선·원·호·사각형·문자·이동·복사·모깎기·자르기·지우기·치수 12개 도구와 끝점·직교 스냅, 수치 키패드로 사무실 CAD와 같은 방식으로 그립니다. 도형을 선택하면 레이어·색·굵기·선종류를 팔레트에서 바로 바꿉니다. 자세한 것은 <a href=\"/guides/edit-cad-drawings-on-ipad/\">아이패드 CAD 앱으로 실제 도면 수정하는 방법</a>에 있습니다."),
    ("h2","Apple Pencil 마크업"),
    ("p","CAD 도형을 건드리지 않고 표시만 남기려면 마크업 모드를 씁니다. 펜·마커·연필 획은 도면 좌표에 고정돼 확대·이동 뒤에도 같은 자리에 있고, 핀에 사진과 메모를 달면 위치가 곧 기록이 됩니다. <a href=\"/guides/apple-pencil-cad-markup/\">Apple Pencil로 CAD 도면 마크업하기</a>를 참고하세요."),
    ("h2","축척 맞춰 플롯"),
    ("p","플롯 PDF는 지정한 축척과 100mm 검증 눈금을 달고 나갑니다. 출력물의 눈금이 100mm면 프린터 배율이 걸리지 않은 것입니다. 마크업 잉크와 핀도 같은 좌표로 인쇄됩니다. 순서는 <a href=\"/guides/plot-scale-pdf-ipad/\">아이패드에서 CAD 도면 축척 PDF 출력하기</a>에 있습니다."),
    ("h2","정리"),
    ("ul",["가장 확실한 길은 PC에서 DXF로 저장해 가져가는 것입니다.",
          "DWG를 직접 열 때는 레이어·선종류 유지 여부와 '못 가져온 요소를 알려 주는가'를 확인하세요.",
          "단위를 묻는 앱을 쓰세요. 축척은 여기서 결정됩니다."]),
   ],
   cta="iPad에서 실제 CAD 도면 편집이 필요한 경우 Fluxketch에서 DWG·DXF를 레이어 그대로 열어볼 수 있습니다. 베타 기간에는 모든 기능이 무료입니다.",
  ),
  en=dict(
   title="How to open DWG files on iPad — view and edit CAD drawings on the spot",
   short="Open DWG on iPad", desc="Three ways to open DWG files on iPad, why layers and linetypes get lost, and the steps to open and edit a DWG with its layers intact.",
   h1="How to open DWG files on iPad",
   lead="When a DWG lands on your iPad in the field, here is what works, what doesn't, and how to open it without losing layers — in order.",
   body=[
    ("h2","What DWG is"),
    ("p","DWG is AutoCAD's native format. It is binary — not human-readable — and its internal structure changes by version (R14, 2000, 2004, 2007, 2010, 2013, 2018). Any program other than AutoCAD needs its own engine to interpret it, and the quality of that engine decides whether layers survive and linetypes are right."),
    ("p","The same drawing written out as text is DXF, an open format any CAD can read and write. The differences are covered in <a href=\"/en/guides/dwg-vs-dxf/\">DWG vs DXF</a>."),
    ("h2","What usually goes wrong on iPad"),
    ("ul",["<b>Layers disappear.</b> A viewer that flattens the DWG into one picture can't toggle layers, and the drawing can't go back.",
          "<b>Weights and linetypes collapse.</b> Dashed and dash-dot lines shown as solid, heavy wall lines shown thin — the drawing reads wrong.",
          "<b>Some lines are missing.</b> Many apps skip multilines (MLINE), 3D faces and entities drawn in an arbitrary coordinate system (OCS). You won't know unless the app tells you.",
          "<b>The scale is off.</b> Read a millimetre drawing as metres and it is 1,000 times too small. Apps that don't ask for the unit fail here.",
          "<b>Large files won't open.</b> DWG grows four to six times as DXF, and some apps reject it at that size."]),
    ("h2","Three ways to open a DWG on iPad"),
    ("ol",["<b>Save as DXF on the PC and take that.</b> The surest route. In AutoCAD, Save As → DXF (2018 ASCII), then move it over iCloud or AirDrop. It opens offline from the start, even on a site with no coverage.",
          "<b>Use an app that opens DWG directly.</b> The app converts it. Whether conversion runs on the device or a server, whether layers and linetypes survive, and whether skipped elements are reported all differ by app.",
          "<b>Print to PDF.</b> The choice when you only need to look. With a known scale you can still mark up on top."]),
    ("h2","Opening with layers intact (in Fluxketch)"),
    ("fig","layers-sheet","Layer panel after opening a DWG — 188 layers with color, weight and linetype","After opening a DWG, all 188 layers arrive with color, weight and linetype."),
    ("ol",["Tap <b>Import</b> on the dashboard and pick the DWG from the Files app, iCloud or a mail attachment. If iCloud hasn't downloaded it yet, the app waits for the download before reading.",
          "The conversion server turns DWG into DXF (LibreDWG-based, R14 to 2018). This is the only step that needs a connection.",
          "The <b>import report</b> lists layer and entity counts plus anything skipped by type and count. Multileaders, wipeouts and regions aren't supported yet, so check here.",
          "Entities on frozen or off layers are imported but hidden, and the app says so. Turn the layer on in the panel and they appear."]),
    ("note","A DWG <b>truncated</b> in transit by mail or chat won't open in any app. If the conversion server reports a missing end-of-file, get the original again."),
    ("h2","Selecting and editing CAD objects"),
    ("p","Once open, it's CAD, not a viewer. Twelve tools — line, polyline, circle, arc, rectangle, text, move, copy, fillet, trim, erase, dimension — with endpoint and ortho snaps and a numeric keypad, the same way you draw at the office. Select an entity and change its layer, color, weight and linetype in the palette. Details in <a href=\"/en/guides/edit-cad-drawings-on-ipad/\">How to edit real drawings with a CAD app on iPad</a>."),
    ("h2","Apple Pencil markup"),
    ("p","To leave marks without touching CAD entities, use markup mode. Pen, marker and pencil strokes are locked to drawing coordinates, so they stay put after zoom and pan, and a pin with a photo and note makes the position the record. See <a href=\"/en/guides/apple-pencil-cad-markup/\">Marking up CAD drawings with Apple Pencil</a>."),
    ("h2","Plotting to scale"),
    ("p","Plot PDFs carry the chosen scale and a 100 mm check ruler. If the ruler measures 100 mm on paper, the printer didn't rescale. Markup ink and pins print at the same coordinates. Steps in <a href=\"/en/guides/plot-scale-pdf-ipad/\">Plotting CAD drawings to scale PDF from iPad</a>."),
    ("h2","In short"),
    ("ul",["The surest route is saving as DXF on the PC.",
          "When opening DWG directly, check that layers and linetypes survive and that skipped elements are reported.",
          "Use an app that asks for the unit. Scale is decided there."]),
   ],
   cta="If you need real CAD editing on iPad, Fluxketch opens DWG and DXF with layers intact. Everything is free during the beta.",
  )),
 dict(slug="edit-cad-drawings-on-ipad", img="structural-dark",
  ko=dict(
   title="아이패드 CAD 앱으로 실제 도면 수정하는 방법 — 도구·스냅·레이어·내보내기",
   short="아이패드 CAD로 도면 수정하기", desc="iPad CAD 앱에서 실제 도면을 수정하는 순서: 선택, 이동·복사·자르기, 스냅과 수치 입력, 레이어 속성 변경, DXF 내보내기까지 현장 기준으로 정리했습니다.",
   h1="아이패드 CAD 앱으로 실제 도면 수정하는 방법",
   lead="벽선 하나 옮기고 치수 하나 넣는 일도 뷰어로는 안 됩니다. iPad에서 CAD 편집이 되려면 무엇이 갖춰져야 하는지, 실제 순서대로 씁니다.",
   body=[
    ("h2","편집기와 뷰어를 가르는 다섯 가지"),
    ("ul",["<b>선택.</b> 탭·올가미로 도형을 고르고, 잠긴 레이어는 선택에서 빠져야 합니다.",
          "<b>스냅.</b> 끝점·직교 스냅이 없으면 선이 붙지 않습니다. 화면 확대에 따라 스냅 반경이 같이 움직여야 합니다.",
          "<b>수치 입력.</b> 손끝으로는 3,600mm를 정확히 못 찍습니다. 길이·각도를 키패드로 넣을 수 있어야 합니다.",
          "<b>레이어 속성.</b> 색·굵기·선종류를 레이어 단위로 바꾸고, 숨긴 레이어는 스냅과 플롯에서도 빠져야 합니다.",
          "<b>되돌리기와 내보내기.</b> 되돌리기가 CAD·마크업 모두에 걸리고, 결과가 DXF로 사무실에 돌아가야 합니다."]),
    ("h2","1. 도면을 열고 단위를 확인한다"),
    ("p","DXF는 열 때 단위(mm·cm·m·inch·ft)를 확인합니다. 여기서 틀리면 뒤의 치수·축척이 전부 틀립니다. DWG는 한 번 변환한 뒤 같은 절차입니다(<a href=\"/guides/open-dwg-on-ipad/\">아이패드에서 DWG 여는 방법</a>)."),
    ("h2","2. 도면 보기와 CAD 모드를 오간다"),
    ("p","흰 바탕 <b>도면 보기</b>는 인쇄물처럼 검은 선으로 봅니다. 어두운 <b>CAD 모드</b>는 레이어 색 그대로 보여 주므로 어느 레이어인지 한눈에 압니다. 편집은 어디서든 되고, 획과 핀은 모드를 오가도 제자리입니다."),
    ("fig","structural-dark","배근 상세 도면 — CAD 모드, 왼쪽 도구 팔레트와 오른쪽 스냅 레일","CAD 모드: 왼쪽이 도구 12종, 오른쪽이 스냅·직교 레일."),
    ("h2","3. 선택하고 옮기고 자른다"),
    ("ol",["<b>선택</b>: 도형을 탭하거나 올가미로 여러 개를 감쌉니다. 잠근 레이어의 도형은 걸리지 않습니다.",
          "<b>이동·복사</b>: 기준점을 찍고 목표점을 찍습니다. 끝점 스냅이 켜져 있으면 다른 도형의 끝에 정확히 붙습니다. 거리는 키패드로 넣을 수 있습니다.",
          "<b>자르기·지우기</b>: 경계를 고르고 잘라 낼 쪽을 탭합니다. 지우기는 선택한 것만 지웁니다.",
          "<b>모깎기</b>: 두 선을 고르면 반지름만큼 둥글게 잇습니다.",
          "<b>되돌리기</b>: 상단의 되돌리기·다시 실행이 CAD와 마크업 양쪽에 걸립니다."]),
    ("h2","4. 그린다 — 선·폴리선·원·호·사각형·문자·치수"),
    ("p","직교를 켜면 수평·수직으로만 그려지고, 끝점 스냅은 기존 도형의 끝에 붙습니다. 길이는 키패드로 넣고, 치수 도구는 두 점을 찍으면 실제 길이를 단위와 함께 씁니다. 문자는 레이어 색을 따릅니다."),
    ("h2","5. 레이어 속성을 바꾼다"),
    ("p","레이어 패널에서 가시성·잠금·색·굵기·선종류를 바로 바꿉니다. 검색으로 레이어 188개 중 원하는 것을 찾습니다. 레이어를 끄면 화면·스냅·플롯이 같은 규칙으로 그 레이어를 뺍니다. 도형 하나만 색을 바꾸려면 도형을 선택해 '자기 색'을 줍니다. 시트가 도형 색을 레이어 색으로 강제하는 경우 앱이 그 사실을 알려 줍니다."),
    ("note","<b>큰 도면 팁.</b> 18만 도형 도면에서도 팬·줌은 60Hz로 따라오지만, 편집 중에는 필요한 레이어만 켜 두는 것이 눈에도 손에도 빠릅니다."),
    ("h2","6. 내보낸다"),
    ("p","더보기 메뉴의 <b>DXF 내보내기</b>로 레이어·색·굵기·선종류 그대로 사무실 CAD에 돌려보냅니다. 플롯 PDF는 축척과 100mm 검증 눈금을 달고 나가며 마크업과 핀을 함께 인쇄합니다. DWG 저장은 아직 지원하지 않으므로 PC CAD에서 DXF를 열어 DWG로 저장합니다."),
    ("h2","iPad에서 하지 않는 것이 나은 일"),
    ("ul",["3D 모델링, 외부 참조(Xref)가 많은 대형 세트 정리, 수십 장 일괄 플롯은 사무실 PC에 남겨 두세요.",
          "iPad는 현장에서 확인·수정·기록·출력하는 자리입니다. 역할 구분은 <a href=\"/guides/mobile-cad-vs-desktop-cad/\">모바일 CAD와 노트북 CAD의 차이</a>에 있습니다."]),
   ],
   cta="위 순서는 Fluxketch 기준입니다. iPad에서 실제 CAD 도면 편집이 필요한 경우 DWG·DXF를 그대로 열어 시험해 보세요.",
  ),
  en=dict(
   title="How to edit real drawings with a CAD app on iPad — tools, snaps, layers, export",
   short="Edit drawings with iPad CAD", desc="The order of editing a real drawing in an iPad CAD app: selecting, move/copy/trim, snaps and numeric input, layer properties and DXF export, from a field point of view.",
   h1="How to edit real drawings with a CAD app on iPad",
   lead="Moving one wall line or adding one dimension is beyond a viewer. Here is what iPad CAD editing needs, in the order you'd actually do it.",
   body=[
    ("h2","Five things that separate an editor from a viewer"),
    ("ul",["<b>Selection.</b> Tap or lasso entities, and locked layers must be excluded.",
          "<b>Snaps.</b> Without endpoint and ortho snaps lines don't join. The snap radius has to follow the zoom.",
          "<b>Numeric input.</b> A fingertip can't hit 3,600 mm. Lengths and angles need a keypad.",
          "<b>Layer properties.</b> Color, weight and linetype per layer, and hidden layers must leave snaps and plots too.",
          "<b>Undo and export.</b> Undo must cover CAD and markup, and the result must go back to the office as DXF."]),
    ("h2","1. Open and confirm the unit"),
    ("p","DXF confirms its unit (mm, cm, m, inch, ft) on open. Get this wrong and every dimension and scale after it is wrong. DWG follows the same steps after one conversion (<a href=\"/en/guides/open-dwg-on-ipad/\">How to open DWG on iPad</a>)."),
    ("h2","2. Switch between sheet view and CAD mode"),
    ("p","White <b>sheet view</b> shows black lines like a print. Dark <b>CAD mode</b> shows layer colors so you know which layer is which at a glance. Editing works in both, and strokes and pins stay put when you switch."),
    ("fig","structural-dark","Rebar detail drawing in CAD mode with the tool palette on the left and the snap rail on the right","CAD mode: twelve tools on the left, snap and ortho rail on the right."),
    ("h2","3. Select, move, trim"),
    ("ol",["<b>Select</b>: tap an entity or lasso several. Entities on locked layers are skipped.",
          "<b>Move and copy</b>: tap a base point, then a target. With endpoint snap on, it lands exactly on another entity's end. Distances can be typed on the keypad.",
          "<b>Trim and erase</b>: pick the boundary, tap the side to remove. Erase removes only the selection.",
          "<b>Fillet</b>: pick two lines and they join with a rounded corner of the given radius.",
          "<b>Undo</b>: the undo and redo buttons at the top cover both CAD and markup."]),
    ("h2","4. Draw — line, polyline, circle, arc, rectangle, text, dimension"),
    ("p","With ortho on you draw only horizontal and vertical; endpoint snap joins existing ends. Type lengths on the keypad, and the dimension tool writes the real length with units from two points. Text follows the layer color."),
    ("h2","5. Change layer properties"),
    ("p","Visibility, lock, color, weight and linetype change right in the layer panel; search finds one of 188 layers. Turn a layer off and the screen, snaps and plots exclude it by the same rule. To recolor one entity, select it and give it an explicit color. If a sheet forces entity colors to the layer color, the app tells you."),
    ("note","<b>Big-drawing tip.</b> Pan and zoom hold 60 Hz on 180,000 entities, but keeping only the layers you need on while editing is faster for both eyes and hands."),
    ("h2","6. Export"),
    ("p","<b>DXF export</b> in the More menu returns layers, colors, weights and linetypes to office CAD as they are. Plot PDFs carry the scale and a 100 mm check ruler and print markup and pins. Saving to DWG isn't supported yet; open the DXF in PC CAD and save as DWG."),
    ("h2","What is better left off the iPad"),
    ("ul",["3D modeling, tidying large sets with many external references (Xrefs) and batch-plotting dozens of sheets belong on the office PC.",
          "The iPad is where you check, fix, record and print on site. The split is covered in <a href=\"/en/guides/mobile-cad-vs-desktop-cad/\">Mobile CAD vs laptop CAD</a>."]),
   ],
   cta="The steps above are Fluxketch's. If you need real CAD editing on iPad, open your DWG or DXF as it is and try it.",
  )),
 dict(slug="dwg-vs-dxf", img="sections-sheet",
  ko=dict(
   title="DWG와 DXF의 차이 — 언제 무엇으로 저장해야 하나",
   short="DWG와 DXF 차이", desc="DWG와 DXF는 같은 도면의 두 형식입니다. 구조·크기·호환성 차이와 iPad·다른 CAD로 넘길 때 어느 쪽을 골라야 하는지 표로 정리했습니다.",
   h1="DWG와 DXF의 차이",
   lead="둘 다 AutoCAD 도면이지만 쓰임이 다릅니다. 무엇이 같고 무엇이 다른지, 다른 프로그램이나 iPad로 넘길 때 어느 쪽을 골라야 하는지 정리했습니다.",
   body=[
    ("h2","한 줄 요약"),
    ("p","<b>DWG</b>는 AutoCAD의 이진 저장 형식이고, <b>DXF</b>(Drawing Exchange Format)는 같은 내용을 텍스트로 풀어 쓴 교환 형식입니다. 회사 안에서는 DWG, 다른 프로그램·다른 기기로 넘길 때는 DXF입니다."),
    ("h2","비교"),
    ("table",["항목","DWG","DXF"],[
      ["구조","이진, 버전별로 다름","텍스트(ASCII), 그룹 코드·값 쌍"],
      ["파일 크기","작다","같은 도면이 4~6배 크다"],
      ["열 수 있는 프로그램","AutoCAD와 DWG 엔진을 가진 프로그램","거의 모든 CAD·GIS·CAM"],
      ["레이어·색·굵기·선종류","보존","보존"],
      ["블록·해치·치수","보존","보존(치수 스타일은 프로그램마다 해석 차이)"],
      ["외부 참조(Xref)","경로로 연결","경로로 연결(파일에 포함되지 않음)"],
      ["손상 시","도구 없이는 복구 어려움","텍스트라 부분 복구 가능"],
      ["인터넷 없이 iPad에서","변환 필요(앱마다 다름)","Fluxketch는 직접 읽음(오프라인)"],
    ]),
    ("h2","DXF가 커지는 이유"),
    ("p","DXF는 모든 값을 텍스트로 씁니다. 좌표 하나가 이진에서는 8바이트지만 텍스트에서는 그룹 코드 줄(10)과 값 줄(123456.789012) 두 줄로 풀려 자릿수만큼 커집니다. 그래서 같은 도면이 4~6배 커지지만, 도형 개수는 같습니다. iPad 앱이 열 수 있는지를 판단할 때는 파일 크기가 아니라 <b>도형 개수와 기기 메모리</b>를 봐야 합니다."),
    ("h2","언제 DWG로, 언제 DXF로"),
    ("ul",["<b>같은 AutoCAD 사용자끼리</b>: DWG. 작고 빠릅니다.",
          "<b>다른 CAD(BricsCAD·ZWCAD·DraftSight 등)로</b>: 둘 다 열리지만 DXF가 안전합니다.",
          "<b>iPad·모바일로</b>: DXF(2018 ASCII)로 저장하면 어느 앱이든 오프라인으로 엽니다.",
          "<b>레이저·CNC·GIS로</b>: DXF. 대부분 DXF만 받습니다.",
          "<b>보관</b>: DWG와 DXF를 함께 두면 나중에 어느 프로그램으로도 열립니다."]),
    ("h2","변환할 때 확인할 것"),
    ("ol",["<b>단위.</b> DXF 헤더의 $INSUNITS가 비어 있는 파일이 많습니다. 여는 쪽이 단위를 물어봐야 합니다.",
          "<b>버전.</b> 오래된 프로그램용이면 2000·2004 DXF로 저장합니다. 최신 요소(다중 지시선 등)는 옛 버전에 없습니다.",
          "<b>외부 참조.</b> Xref는 파일에 포함되지 않습니다. 넘기기 전에 바인드(삽입)하세요.",
          "<b>글꼴.</b> SHX·TTF 글꼴은 파일에 없습니다. 여는 쪽에 없으면 대체 글꼴로 보입니다."]),
    ("fig","sections-sheet","단면·입면 시트 — DXF로 열어 도면 보기","DXF로 넘긴 단면·입면 도면. 해치·치수·문자가 벡터로 유지된 상태."),
    ("h2","iPad에서의 선택"),
    ("p","현장에 나가기 전에 DXF로 저장해 두면 인터넷 없이 열립니다. DWG밖에 없다면 DWG를 직접 여는 앱이 필요하고, 그 앱이 변환 뒤 레이어·선종류를 유지하는지, 못 가져온 요소를 알려 주는지가 중요합니다. 자세한 것은 <a href=\"/guides/open-dwg-on-ipad/\">아이패드에서 DWG 파일 여는 방법</a>에 있습니다."),
   ],
   cta="Fluxketch는 DXF를 iPad에서 직접 읽고(오프라인), DWG는 변환해 엽니다. 편집 결과는 DXF로 돌려보냅니다.",
  ),
  en=dict(
   title="DWG vs DXF — which one to save, and when",
   short="DWG vs DXF", desc="DWG and DXF are two formats of the same drawing. Structure, size and compatibility differences, and which to choose when handing drawings to iPad or another CAD, in one table.",
   h1="DWG vs DXF: the difference",
   lead="Both are AutoCAD drawings, but they serve different jobs. What's the same, what differs, and which to pick when the drawing leaves your program or goes to an iPad.",
   body=[
    ("h2","One line"),
    ("p","<b>DWG</b> is AutoCAD's binary native format; <b>DXF</b> (Drawing Exchange Format) is the same content written out as text for exchange. Inside the company, DWG. Handing off to another program or device, DXF."),
    ("h2","Comparison"),
    ("table",["Item","DWG","DXF"],[
      ["Structure","Binary, changes by version","Text (ASCII), group code / value pairs"],
      ["File size","Small","Same drawing 4–6× larger"],
      ["Programs that open it","AutoCAD and programs with a DWG engine","Almost every CAD, GIS and CAM"],
      ["Layers, colors, weights, linetypes","Kept","Kept"],
      ["Blocks, hatches, dimensions","Kept","Kept (dimension styles vary by program)"],
      ["External references (Xref)","Linked by path","Linked by path (not embedded)"],
      ["When damaged","Hard to recover without tools","Text, so partial recovery is possible"],
      ["On iPad without a connection","Needs conversion (app-dependent)","Fluxketch reads it directly, offline"],
    ]),
    ("h2","Why DXF is bigger"),
    ("p","DXF writes every value as text. One coordinate is 8 bytes in binary but as text it becomes two lines — a group code (10) and a value (123456.789012) — as long as its digits. The same drawing grows four to six times, yet the entity count is identical. Whether an iPad app can open it should depend on <b>entity count and device memory</b>, not file size."),
    ("h2","When DWG, when DXF"),
    ("ul",["<b>Between AutoCAD users</b>: DWG. Small and fast.",
          "<b>To another CAD (BricsCAD, ZWCAD, DraftSight…)</b>: both open, DXF is the safe bet.",
          "<b>To iPad or mobile</b>: save as DXF (2018 ASCII) and any app opens it offline.",
          "<b>To laser, CNC or GIS</b>: DXF. Most accept only DXF.",
          "<b>Archiving</b>: keep both, and any future program will open one of them."]),
    ("h2","Check before converting"),
    ("ol",["<b>Unit.</b> Many DXFs have an empty $INSUNITS header. The opening side must ask.",
          "<b>Version.</b> For older programs save as 2000 or 2004 DXF. Newer elements (multileaders and so on) don't exist in old versions.",
          "<b>External references.</b> Xrefs aren't embedded. Bind (insert) them before handing off.",
          "<b>Fonts.</b> SHX and TTF fonts aren't in the file. If the opening side lacks them, a substitute is shown."]),
    ("fig","sections-sheet","Sections and elevations sheet opened from DXF in sheet view","Sections and elevations handed over as DXF — hatches, dimensions and text still vector."),
    ("h2","The iPad choice"),
    ("p","Save as DXF before leaving for site and it opens with no connection. If all you have is DWG you need an app that opens it directly, and what matters is whether layers and linetypes survive conversion and whether skipped elements are reported. Details in <a href=\"/en/guides/open-dwg-on-ipad/\">How to open DWG files on iPad</a>."),
   ],
   cta="Fluxketch reads DXF directly on iPad (offline) and converts DWG to open it. Edits go back as DXF.",
  )),
 dict(slug="plot-scale-pdf-ipad", img="ruler-popover",
  ko=dict(
   title="아이패드에서 CAD 도면 축척 PDF 출력하기 — 1:100이 정말 1:100인지 확인하는 법",
   short="축척 PDF 출력하기", desc="CAD 도면을 iPad에서 1:50·1:100 축척 PDF로 플롯하는 순서와 축척 계산, 프린터 '페이지에 맞춤'을 잡아내는 100mm 검증 눈금 사용법을 정리했습니다.",
   h1="아이패드에서 CAD 도면 축척 PDF 출력하기",
   lead="출력물은 축척이 맞아야 자로 잴 수 있습니다. 축척이 무엇인지부터 프린터가 몰래 줄이는 것을 잡는 법까지, 실제 순서대로 씁니다.",
   body=[
    ("h2","축척은 무엇을 뜻하나"),
    ("p","1:100은 종이 위 1mm가 실제 100mm라는 뜻입니다. 실제 3,600mm 벽은 1:100에서 36mm, 1:50에서 72mm로 그려집니다. 도면의 단위(mm·m)가 틀리면 축척도 같이 틀리므로 <b>단위 확인이 축척의 시작</b>입니다."),
    ("table",["실제 길이","1:50","1:100","1:200"],[
      ["1 m","20 mm","10 mm","5 mm"],
      ["3.6 m","72 mm","36 mm","18 mm"],
      ["10 m","200 mm","100 mm","50 mm"],
    ]),
    ("h2","종이에서 축척이 틀어지는 세 가지 원인"),
    ("ol",["<b>도면 단위가 틀렸다.</b> mm 도면을 m로 읽으면 1,000배 작아집니다. 여는 순간 단위를 확인해야 합니다.",
          "<b>PDF가 축척 없이 만들어졌다.</b> '화면 캡처'나 '페이지에 맞춤'으로 만든 PDF에는 축척이 없습니다.",
          "<b>프린터가 줄였다.</b> 인쇄 대화상자의 '페이지에 맞춤'이 켜져 있으면 A3 도면이 94%로 줄어듭니다. 가장 흔하고 가장 늦게 발견됩니다."]),
    ("h2","100mm 검증 눈금"),
    ("p","세 번째 원인을 잡는 가장 쉬운 방법은 <b>종이 위에 100mm 눈금을 함께 인쇄</b>하는 것입니다. 출력물의 눈금을 자로 재서 100mm면 축척이 맞고, 94mm면 프린터 배율이 걸린 것입니다. 우리 축척이 틀린 것과 프린터가 줄인 것을 가르는 자 역할입니다."),
    ("fig","ruler-popover","실척 자 팝오버 — 1:1부터 1:1,000까지 축척과 자로 맞추기","화면에서도 실척으로 봅니다: 1:1~1:1,000 축척과 실제 자로 맞추기."),
    ("h2","iPad에서 플롯하는 순서(Fluxketch 기준)"),
    ("ol",["도면을 열 때 <b>단위</b>를 확인합니다(mm·cm·m·inch·ft).",
          "더보기 메뉴에서 <b>플롯</b>을 고르고 축척(1:1~1:1,000)과 용지를 정합니다.",
          "플롯은 백그라운드에서 렌더링되므로 화면이 멈추지 않습니다. 끝나면 공유 시트가 열립니다.",
          "AirPrint 프린터·메일·메신저·파일 앱으로 보냅니다. 프린터에서는 <b>'실제 크기'</b>(배율 100%)를 고릅니다.",
          "출력물의 <b>100mm 눈금</b>을 자로 잽니다. 100mm가 아니면 인쇄 설정을 고쳐 다시 뽑습니다."]),
    ("note","마크업 잉크와 핀은 도면과 같은 좌표로 함께 인쇄됩니다. 도면 보기의 흰 바탕·검은 선 규칙이 적용되고, 바탕 테두리는 넣지 않습니다."),
    ("h2","시트만 뽑기와 리포트"),
    ("p","여러 시트 중 일부만 필요하면 <b>시트 발행</b>으로 고른 시트만 PDF로 냅니다. 핀의 사진·메모·위치는 별도 <b>리포트</b>(점검·지시·회의 등 7종 서식)로 인쇄됩니다. 회의에는 플롯 PDF 한 장과 리포트 한 부면 됩니다."),
    ("h2","화면에서 실척으로 보기"),
    ("p","종이 없이도 실척으로 볼 수 있습니다. 실척 자는 기종별 화면 밀도를 추정해 1:50이면 1:50으로 보여 주고, '자로 맞추기'로 실제 자와 대조해 보정합니다. 화면에서 두 점을 찍으면 실제 길이가 단위와 함께 나옵니다."),
   ],
   cta="Fluxketch의 플롯 PDF는 축척과 100mm 검증 눈금을 달고 나갑니다. iPad에서 축척 맞춘 출력이 필요하면 베타에서 시험해 보세요.",
  ),
  en=dict(
   title="Plotting CAD drawings to scale PDF from iPad — making sure 1:100 really is 1:100",
   short="Plot to scale PDF", desc="Steps to plot CAD drawings from iPad to 1:50 or 1:100 PDF, the scale arithmetic, and how a 100 mm check ruler catches the printer's 'fit to page'.",
   h1="Plotting CAD drawings to scale PDF from iPad",
   lead="A print is only measurable if the scale is right. From what scale means to catching a printer that quietly shrinks the page, in the order you'd do it.",
   body=[
    ("h2","What scale means"),
    ("p","1:100 means 1 mm on paper is 100 mm in reality. A 3,600 mm wall draws as 36 mm at 1:100 and 72 mm at 1:50. If the drawing's unit (mm or m) is wrong the scale is wrong with it, so <b>confirming the unit is where scale starts</b>."),
    ("table",["Real length","1:50","1:100","1:200"],[
      ["1 m","20 mm","10 mm","5 mm"],
      ["3.6 m","72 mm","36 mm","18 mm"],
      ["10 m","200 mm","100 mm","50 mm"],
    ]),
    ("h2","Three ways scale goes wrong on paper"),
    ("ol",["<b>Wrong drawing unit.</b> Read a millimetre drawing as metres and it's 1,000× too small. Confirm the unit on open.",
          "<b>The PDF was made without scale.</b> A screen capture or a 'fit to page' PDF has no scale.",
          "<b>The printer shrank it.</b> With 'fit to page' on, an A3 drawing prints at 94%. The most common cause and the last to be noticed."]),
    ("h2","The 100 mm check ruler"),
    ("p","The easiest way to catch the third cause is to <b>print a 100 mm ruler on the paper</b>. Measure it: 100 mm means the scale is right; 94 mm means printer scaling kicked in. It's the ruler that separates our scale from the printer's."),
    ("fig","ruler-popover","True-scale ruler popover — scales from 1:1 to 1:1,000 and ruler calibration","True scale on screen too: 1:1 to 1:1,000, calibrated against a real ruler."),
    ("h2","Plotting from iPad (in Fluxketch)"),
    ("ol",["Confirm the <b>unit</b> when the drawing opens (mm, cm, m, inch, ft).",
          "Choose <b>Plot</b> in the More menu and set the scale (1:1 to 1:1,000) and paper size.",
          "Plotting renders in the background, so the screen stays responsive. The share sheet opens when it's done.",
          "Send to an AirPrint printer, Mail, chat or the Files app. On the printer choose <b>actual size</b> (100%).",
          "Measure the <b>100 mm ruler</b> on the print. If it isn't 100 mm, fix the print settings and reprint."]),
    ("note","Markup ink and pins print at the same coordinates as the drawing. Sheet-view rules apply — black lines on white — with no page border."),
    ("h2","Sheets only, and reports"),
    ("p","If you need only some of the sheets, <b>sheet issue</b> exports the ones you pick. Pin photos, notes and positions print as a separate <b>report</b> in seven document formats (inspection, instruction, meeting and more). One plot PDF and one report is enough for a meeting."),
    ("h2","True scale on screen"),
    ("p","You can see true scale without paper. The true-scale ruler estimates each device's screen density so 1:50 shows as 1:50, and calibration checks it against a real ruler. Tap two points on screen and the real length appears with units."),
   ],
   cta="Fluxketch plot PDFs carry the scale and a 100 mm check ruler. If you need scale-true output from iPad, try it in the beta.",
  )),
 dict(slug="apple-pencil-cad-markup", img="vivienda-markup-dark",
  ko=dict(
   title="Apple Pencil로 CAD 도면 마크업하기 — 획이 도면에 붙어 있어야 하는 이유",
   short="Apple Pencil 도면 마크업", desc="iPad와 Apple Pencil로 CAD 도면에 마크업할 때 필요한 것: 도면 좌표 고정, 펜·마커·연필·올가미·자, 사진 핀, 노트, 리포트까지 현장 순서로 정리했습니다.",
   h1="Apple Pencil로 CAD 도면 마크업하기",
   lead="스크린샷 위에 그린 표시는 다음 날 위치를 잃습니다. 현장 마크업이 기록이 되려면 무엇이 필요한지, 도구부터 리포트까지 순서대로 씁니다.",
   body=[
    ("h2","마크업이 기록이 되는 조건"),
    ("ul",["<b>도면 좌표에 고정.</b> 획이 화면 픽셀이 아니라 도면 좌표에 저장돼야 확대·이동·축척 변경 뒤에도 같은 자리에 있습니다.",
          "<b>도면과 함께 저장.</b> 마크업이 도면 파일 안에 있어야 파일을 넘길 때 같이 갑니다.",
          "<b>출력에 포함.</b> 플롯 PDF와 리포트에 잉크와 핀이 인쇄돼야 회의 자료가 됩니다.",
          "<b>사진·메모가 위치를 가짐.</b> 카메라 롤의 사진은 위치를 모릅니다. 핀에 달린 사진은 위치가 곧 기록입니다."]),
    ("h2","도구"),
    ("p","펜·마커·연필·지우개·올가미·자. Apple Pencil의 필압이 그대로 굵기에 반영되고, 색과 굵기는 팔레트에서 고릅니다. 굵기는 <b>도면 단위 기준</b>이라 1:50에서 그린 굵은 마커가 1:100에서도 같은 의미를 갖습니다. 되돌리기·다시 실행은 마크업에도 걸립니다."),
    ("fig","vivienda-markup-dark","마크업 모드 — 아파트 평면 위 마커 표시와 색·굵기 팔레트","마크업 모드: 왼쪽에 펜·마커·연필·지우개·올가미·자, 색·굵기 팔레트."),
    ("h2","손가락과 펜슬의 역할"),
    ("p","화면 이동은 손가락, 그리기는 Apple Pencil입니다. 펜슬로는 화면이 밀리지 않으므로 손바닥을 얹고 그려도 도면이 움직이지 않습니다. 한 손가락 이동 모드에서도 올가미·지우개·이동은 펜슬로 계속 됩니다."),
    ("h2","순서"),
    ("ol",["도면을 열고 하단의 <b>마크업</b> 탭을 누릅니다. 흰 바탕 도면 보기든 어두운 CAD 모드든 상관없습니다.",
          "펜으로 표시하고, 올가미로 감싸 옮기거나 지웁니다. 자를 켜면 직선이 곧게 그어집니다.",
          "<b>핀</b>을 찍고 사진과 메모를 답니다. 핀은 언제나 마크업 위에 있고 도면 좌표에 고정됩니다.",
          "회의 메모는 <b>노트 페이지</b>(백지·줄·도트·모눈·제도 모눈)를 도면 파일 안에 추가해 씁니다.",
          "더보기 메뉴에서 <b>리포트</b>를 고르면 사진·메모·위치가 표 서식으로, <b>플롯</b>을 고르면 잉크와 핀이 도면과 함께 축척 PDF로 나갑니다."]),
    ("note","마크업은 CAD 도형을 건드리지 않습니다. 선을 실제로 옮겨야 하면 CAD 도구를 쓰세요(<a href=\"/guides/edit-cad-drawings-on-ipad/\">아이패드 CAD 앱으로 실제 도면 수정하는 방법</a>)."),
    ("h2","PDF 도면에 마크업하기"),
    ("p","DXF·DWG가 없고 PDF뿐이라면 PDF를 밑그림으로 열어 두 점으로 축척을 맞춥니다. 그 위에 마크업·핀·CAD 작도를 할 수 있고, PDF 안의 벡터 선에 스냅도 됩니다."),
    ("h2","사무실로 넘길 때"),
    ("p","마크업 잉크와 핀은 플롯 PDF와 리포트로 넘깁니다. DXF 내보내기에는 CAD 도형이 나갑니다. 손글씨는 PDF로, 도형은 DXF로 — 현장과 사무실이 각각 받는 것입니다."),
   ],
   cta="Fluxketch의 마크업은 도면 좌표에 고정되고 플롯·리포트에 그대로 인쇄됩니다. iPad와 Apple Pencil로 현장 기록이 필요하면 베타에서 시험해 보세요.",
  ),
  en=dict(
   title="Marking up CAD drawings with Apple Pencil — why strokes must stick to the drawing",
   short="Apple Pencil markup", desc="What CAD markup on iPad with Apple Pencil needs: drawing-coordinate lock, pen/marker/pencil/lasso/ruler, photo pins, notes and reports, in field order.",
   h1="Marking up CAD drawings with Apple Pencil",
   lead="A mark on a screenshot loses its place by the next day. What site markup needs to become a record, from tools to reports, in order.",
   body=[
    ("h2","When markup counts as a record"),
    ("ul",["<b>Locked to drawing coordinates.</b> Strokes stored in drawing coordinates, not screen pixels, stay put after zoom, pan or a scale change.",
          "<b>Saved with the drawing.</b> Markup inside the drawing file travels with it.",
          "<b>Included in output.</b> Ink and pins must print into plot PDFs and reports to become meeting material.",
          "<b>Photos and notes with a position.</b> A camera-roll photo doesn't know where it was. A photo on a pin makes the position the record."]),
    ("h2","Tools"),
    ("p","Pen, marker, pencil, eraser, lasso and ruler. Apple Pencil pressure feeds width directly; color and width come from the palette. Widths are in <b>drawing units</b>, so a heavy marker drawn at 1:50 means the same at 1:100. Undo and redo cover markup too."),
    ("fig","vivienda-markup-dark","Markup mode — marker notes on an apartment plan with the color and width palette","Markup mode: pen, marker, pencil, eraser, lasso and ruler on the left with the color and width palette."),
    ("h2","Fingers and Pencil"),
    ("p","Fingers pan, Apple Pencil draws. The Pencil never pushes the canvas, so you can rest your palm and draw without the drawing moving. In one-finger pan mode, lasso, eraser and move still work with the Pencil."),
    ("h2","Steps"),
    ("ol",["Open the drawing and tap the <b>Markup</b> tab at the bottom. White sheet view or dark CAD mode — either works.",
          "Mark with the pen, lasso to move or erase, and turn the ruler on for straight lines.",
          "Drop a <b>pin</b> and attach a photo and a note. Pins always sit above markup and are locked to drawing coordinates.",
          "Write meeting notes on a <b>note page</b> (blank, ruled, dotted, grid, drafting grid) added inside the drawing file.",
          "Choose <b>Report</b> in the More menu for photos, notes and positions in table layouts, or <b>Plot</b> for ink and pins on a scale PDF with the drawing."]),
    ("note","Markup doesn't touch CAD entities. To actually move a line, use the CAD tools (<a href=\"/en/guides/edit-cad-drawings-on-ipad/\">How to edit real drawings with a CAD app on iPad</a>)."),
    ("h2","Marking up a PDF drawing"),
    ("p","If all you have is a PDF, open it as an underlay and set the scale with two points. Markup, pins and CAD drafting work on top, and you can snap to the PDF's vector lines."),
    ("h2","Handing off to the office"),
    ("p","Markup ink and pins travel as plot PDF and report. DXF export carries CAD entities. Handwriting as PDF, geometry as DXF — what the site and the office each receive."),
   ],
   cta="Fluxketch markup is locked to drawing coordinates and prints as-is into plots and reports. If you need site records with iPad and Apple Pencil, try the beta.",
  )),
 dict(slug="mobile-cad-vs-desktop-cad", img="granada-topo-dark",
  ko=dict(
   title="모바일 CAD와 노트북 CAD의 차이 — 현장에서 무엇을 iPad에 맡길까",
   short="모바일 CAD vs 노트북 CAD", desc="iPad 같은 모바일 CAD와 노트북·PC CAD는 역할이 다릅니다. 각각 잘하는 일과 못하는 일, 현장에서 두 가지를 나누는 기준을 정리했습니다.",
   h1="모바일 CAD와 노트북 CAD의 차이",
   lead="노트북을 현장에 들고 나가 본 사람은 압니다. 문제는 성능이 아니라 자세입니다. 무엇을 iPad에 맡기고 무엇을 사무실에 남길지 기준을 정리했습니다.",
   body=[
    ("h2","도구가 아니라 자세의 차이"),
    ("p","노트북 CAD는 앉아서, 두 손으로, 마우스와 키보드로 씁니다. 모바일 CAD는 서서, 한 손으로 들고, 다른 손의 펜으로 씁니다. 그래서 같은 '편집'이라도 현장에서 필요한 편집은 <b>확인·수정·기록·출력</b>이고, 사무실의 편집은 <b>설계·정리·세트 관리</b>입니다."),
    ("h2","비교"),
    ("table",["항목","노트북·PC CAD","모바일 CAD(iPad)"],[
      ["자세","앉아서 두 손","서서 한 손 + 펜"],
      ["입력","마우스·키보드·명령행","Apple Pencil·터치·키패드"],
      ["잘하는 일","설계·대량 편집·Xref 세트·일괄 플롯","현장 확인·수정·마크업·핀·축척 출력"],
      ["오프라인","가능","DXF·PDF 가능(DWG는 첫 변환만 온라인)"],
      ["사진·메모","별도 앱","핀에 달려 위치가 기록"],
      ["3D","가능","Fluxketch는 2D 전용"],
      ["부팅·준비","분 단위","초 단위"],
      ["결과 전달","DWG·PDF","DXF·플롯 PDF·리포트"],
    ]),
    ("h2","iPad에 맡길 일"),
    ("ul",["<b>현장 확인.</b> 실척 자로 1:50 그대로 보고, 두 점을 찍어 길이를 잽니다.",
          "<b>작은 수정.</b> 벽선 하나, 치수 하나, 문자 하나. 스냅과 키패드가 있으면 그 자리에서 끝납니다.",
          "<b>기록.</b> 사진 핀·마크업·노트가 도면 좌표에 붙어 위치가 곧 기록입니다.",
          "<b>출력.</b> 축척 맞춘 플롯 PDF와 리포트를 회의 자리에서 바로 보냅니다."]),
    ("h2","사무실에 남길 일"),
    ("ul",["3D 모델링과 렌더링.",
          "외부 참조(Xref)가 얽힌 대형 세트 정리, 수십 장 일괄 플롯.",
          "DWG 저장. 모바일에서 DXF로 받은 파일을 사무실 CAD가 DWG로 저장합니다.",
          "치수 스타일·도면 템플릿 같은 표준 관리."]),
    ("fig","granada-topo-dark","그라나다 지형도 — 시가지와 산악 등고선 전체를 iPad CAD 모드에 올린 화면","성능은 더 이상 이유가 아닙니다: 등고선 전체를 올린 지형도가 iPad에서 손을 따라옵니다."),
    ("h2","'성능이 부족하다'는 이제 이유가 아니다"),
    ("p","M 시리즈 iPad는 18만 도형 도면에서 팬·줌을 60Hz로 따라오고, 레이어 188개를 그대로 다룹니다. 메모리 관문이 기기 가용량을 보고 열 수 있는지 먼저 판단하므로 '열다가 죽는' 일이 아니라 '열 수 없는 이유를 말하는' 일이 됩니다. 남는 차이는 자세와 입력 방식뿐입니다."),
    ("h2","두 가지를 잇는 것: 왕복"),
    ("p","사무실에서 DWG·DXF로 내보내고, 현장 iPad에서 열어 손대고, DXF와 플롯 PDF·리포트로 돌려보냅니다. 레이어·색·굵기·선종류가 왕복에서 유지되면 다시 그릴 일이 없습니다. 형식 선택은 <a href=\"/guides/dwg-vs-dxf/\">DWG와 DXF의 차이</a>, 여는 방법은 <a href=\"/guides/open-dwg-on-ipad/\">아이패드에서 DWG 여는 방법</a>에 있습니다."),
   ],
   cta="Fluxketch는 위 표의 '모바일 CAD(iPad)' 열을 맡는 앱입니다. 현장 확인·수정·기록·출력이 필요하면 베타에서 시험해 보세요.",
  ),
  en=dict(
   title="Mobile CAD vs laptop CAD — what to hand to the iPad on site",
   short="Mobile vs laptop CAD", desc="Mobile CAD on iPad and laptop or PC CAD have different jobs. What each does well and poorly, and how to split the work on site.",
   h1="Mobile CAD vs laptop CAD",
   lead="Anyone who has carried a laptop onto a site knows: the problem isn't performance, it's posture. Here is how to decide what goes to the iPad and what stays at the office.",
   body=[
    ("h2","A difference of posture, not tools"),
    ("p","Laptop CAD is used sitting down, two hands, mouse and keyboard. Mobile CAD is used standing, one hand holding, the other with a pen. So even though both are 'editing', the site needs <b>check, fix, record, print</b>, while the office does <b>design, tidy, manage sets</b>."),
    ("h2","Comparison"),
    ("table",["Item","Laptop / PC CAD","Mobile CAD (iPad)"],[
      ["Posture","Seated, two hands","Standing, one hand + pen"],
      ["Input","Mouse, keyboard, command line","Apple Pencil, touch, keypad"],
      ["Good at","Design, bulk edits, Xref sets, batch plotting","Site checks, fixes, markup, pins, scale output"],
      ["Offline","Yes","DXF and PDF yes (DWG needs a connection only for first conversion)"],
      ["Photos and notes","Separate apps","On pins — position is the record"],
      ["3D","Yes","Fluxketch is 2D only"],
      ["Boot and setup","Minutes","Seconds"],
      ["Handoff","DWG, PDF","DXF, plot PDF, report"],
    ]),
    ("h2","What to hand to the iPad"),
    ("ul",["<b>Site checks.</b> See 1:50 as 1:50 with the true-scale ruler and measure between two taps.",
          "<b>Small fixes.</b> One wall line, one dimension, one text. With snaps and a keypad it's done on the spot.",
          "<b>Records.</b> Photo pins, markup and notes stick to drawing coordinates — the position is the record.",
          "<b>Output.</b> Send a scale-true plot PDF and a report from the meeting itself."]),
    ("h2","What stays at the office"),
    ("ul",["3D modeling and rendering.",
          "Tidying large sets tangled with external references, batch-plotting dozens of sheets.",
          "Saving to DWG. Office CAD saves the DXF that came back from mobile as DWG.",
          "Standards — dimension styles, drawing templates."]),
    ("fig","granada-topo-dark","Granada terrain map — city and full mountain contours in iPad CAD mode","Performance is no longer the reason: a terrain map with every contour follows your hand on iPad."),
    ("h2","'Not enough performance' is no longer the reason"),
    ("p","M-series iPads pan and zoom at 60 Hz on a 180,000-entity drawing and handle 188 layers as-is. A memory gate checks the device's free memory before opening, so it's not 'crashes while opening' but 'tells you why it can't'. What remains is posture and input."),
    ("h2","What connects the two: the round trip"),
    ("p","Export DWG or DXF from the office, open and work on the iPad on site, and send back DXF plus a plot PDF and report. When layers, colors, weights and linetypes survive the round trip, nothing gets redrawn. Choosing the format: <a href=\"/en/guides/dwg-vs-dxf/\">DWG vs DXF</a>; opening: <a href=\"/en/guides/open-dwg-on-ipad/\">How to open DWG on iPad</a>."),
   ],
   cta="Fluxketch is the app for the 'Mobile CAD (iPad)' column above. If you need site checks, fixes, records and output, try the beta.",
  )),
]
